version: '3.9'
services:
  nestapp:
    container_name: nestapp
    image: prompt-logger/nestjs
    volumes:
      - type: bind
        source: .
        target: /app
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env

